export const ROUTINE_CATEGORIES = [
  {
    id: "fitness",
    name: "Fitness & Health",
    icon: "🏋️",
    bgLight: "#ecfdf5",
    textLight: "#047857",
    borderLight: "#a7f3d0",
    bgDark: "#064e3b",
    textDark: "#6ee7b7",
    borderDark: "#059669",
  },
  {
    id: "work",
    name: "Work & Career",
    icon: "💼",
    bgLight: "#eff6ff",
    textLight: "#1d4ed8",
    borderLight: "#bfdbfe",
    bgDark: "#1e3a8a",
    textDark: "#93c5fd",
    borderDark: "#2563eb",
  },
  {
    id: "learning",
    name: "Learning & Study",
    icon: "📚",
    bgLight: "#f5f3ff",
    textLight: "#6d28d9",
    borderLight: "#ddd6fe",
    bgDark: "#4c1d95",
    textDark: "#c4b5fd",
    borderDark: "#7c3aed",
  },
  {
    id: "mindfulness",
    name: "Mindfulness & Self-Care",
    icon: "🧘",
    bgLight: "#f0fdfa",
    textLight: "#0f766e",
    borderLight: "#99f6e4",
    bgDark: "#134e4a",
    textDark: "#5eead4",
    borderDark: "#0d9488",
  },
  {
    id: "lifestyle",
    name: "Daily Lifestyle",
    icon: "🌟",
    bgLight: "#fff7ed",
    textLight: "#c2410c",
    borderLight: "#fed7aa",
    bgDark: "#7c2d12",
    textDark: "#fdba74",
    borderDark: "#ea580c",
  },
  {
    id: "finance",
    name: "Finance & Wealth",
    icon: "💰",
    bgLight: "#fffbeb",
    textLight: "#b45309",
    borderLight: "#fde68a",
    bgDark: "#78350f",
    textDark: "#fde047",
    borderDark: "#d97706",
  },
  {
    id: "other",
    name: "General / Other",
    icon: "📌",
    bgLight: "#f3f4f6",
    textLight: "#374151",
    borderLight: "#e5e7eb",
    bgDark: "#374151",
    textDark: "#e5e7eb",
    borderDark: "#4b5563",
  },
];

export const getCategoryMeta = (categoryId) => {
  const found = ROUTINE_CATEGORIES.find((c) => c.id === categoryId);
  return found || ROUTINE_CATEGORIES[4]; // Default to lifestyle
};
